name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # replace with the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.2.0' # replace with your desired Node.js version
      - run: npm install
      - run: npm run build-dev
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/deploy-pages@v2
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - run: npm run deploy
